
spring:
  data:
    neo4j:
      username: neo4j
      password: admin
      uri: 'bolt://localhost:7687'

logging:
  level:
    root: ERROR
    sbb: INFO
  file:
    name: logs/migration.log
  pattern:
    console: "%clr(%d{dd.MM.yyyy HH:mm:ss}){faint} - %msg%n"
    file: "%d{dd.MM.yyyy HH:mm:ss.SSS} %-5level [%thread] %logger : %msg%n"